# This is just a placeholder file that should be replaced with a proper
# snapcraft.yaml. It's here to block snapcraft from executing when the prepare
# script hasn't been run prior to launching snapcraft.
name: '!!! THIS SNAP IS NOT PREPARED - READ ../README AND RUN ../prepare*.sh script !!!'
base: core20 # the base snap is the execution environment for this snap
version: 0.0
summary: Snapping blocker
description: |
  This is just a placeholder file that should be replaced with a proper
  snapcraft.yaml. It's here to block snapcraft from executing when the prepare
  script hasn't been run prior to launching snapcraft.

grade: devel 
confinement: devmode

parts:
  my-part:
    plugin: nil
