# This is a basic workflow to help you get started with Actions

name: Autorelease beta version of checkbox-snap

# Controls when the workflow will run
on:
  push:
    tags:
        - "checkbox-snap-v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  snap:
    strategy:
      matrix:
        type: [classic, uc]
        releases: [16, 18, 20, 22]
    runs-on: ubuntu-latest
    env:
      SERIES: series_${{ matrix.type }}${{ matrix.releases }}
      SERIES_PRETTY:  ${{ matrix.type }} ${{ matrix.releases }}
    name: Snap Checkbox snap for  ${{ matrix.type }}${{ matrix.releases }} series

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Copy over the common files for series ${{ env.SERIES_PRETTY }}
        run: |
          cd checkbox-snap/
          ./prepare_${{ matrix.type }}.sh $SERIES

      - name: Remove '.dev' suffix from the version name
        run: |
          cd checkbox-snap
          # in the following sed onliner the '0,/^version/' bit specifies the range
          # of lines it should act upon, this way only the first occurence of '^version'
          # is getting affected.
          sed -i '0,/^version/s/\(^version\:.*\).dev/\1/' $SERIES/snap/snapcraft.yaml
      - name: add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/provider/launchpad/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/provider/launchpad/credentials
          git config --global user.email "maciej.kisielewski@canonical.com"
          git config --global user.name "Maciej Kisielewski"
      - uses: snapcore/action-build@v1
        id: snapcraft
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
        with:
          path: checkbox-snap/$SERIES
          snapcraft-channel: 7.x/stable
          snapcraft-args: remote-build --build-on amd64,arm64,armhf,i386 --launchpad-accept-public-upload
      - uses: actions/upload-artifact@v3
        with:
          name: snap
          path: checkbox-snap/$SERIES/*.snap
          #path: ${{ steps.snapcraft.outputs.snap }}


