name: remote classic 22

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: copy over common files
        run: |
          cd checkbox-snap/
          ./prepare_classic.sh series_classic22
      - name: add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/provider/launchpad/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/provider/launchpad/credentials
      - uses: snapcore/action-build@v1
        id: snapcraft
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
        with:
          path: checkbox-snap/series_classic22
          snapcraft-channel: 7.x/stable
          snapcraft-args: remote-build --build-on arm64 --launchpad-accept-public-upload
      - uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}



